### ISSUE TITLE
Initialization fails when base geopackage contains a polygon layer

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/mergin-db-sync#28]
Good day

I tried to set up syncing between my Mergin project and Postgres and found that the script fails when I include a polygon layer in the base geopackage. I tried the following:
1. Fix polygon geometries - still fails
2. Convert polygon layer multipart to singe parts - still fails
3. reproject polygon layer from epsg3857 to 4326 - still fails
4. remove polygon layer from geopackage - success, syncing initialized and tested successfully 

* Screenshot  of error:
![mergin-db-sync polygon error](https://user-images.githubusercontent.com/51097011/109970968-5b494d00-7cfe-11eb-97a8-30034392cec4.JPG)

**Comment by wonder-sk** [comment]
Hi Hugo

Can you please make sure that you have 1. updated your git repository to the latest master, and 2. removed the previously built container and build the container again?

It seems like you may be trying the older version as the line numbers in your errors do not match the line numbers of the code in git master...

**Comment by HugoP27** [comment]
Hi Martin

Thanks for pointing that out, I cloned the repo, but forgot to remove and rebuild the docker container 🙈

Unfortunately I still get an error message:

![mergin-db-sync polygon error](https://user-images.githubusercontent.com/51097011/109979722-debb6c00-7d07-11eb-9335-7f47c23cb37d.JPG)

**Comment by wonder-sk** [comment]
Hmm that's strange - it looks like an error we have fixed few weeks ago - https://github.com/lutraconsulting/geodiff/issues/83

But maybe it's something slightly different - could you please share the data privately with me to test it?

**Comment by varmar05** [comment]
Hi @HugoP27,

could you please rebuild your docker image without using cache and try again? If you have built your docker image before, it would use old geodiff version otherwise.

`docker build -t mergin_db_sync . --no-cache`

**Comment by HugoP27** [comment]
Hi @varmar05 
Thanks a lot, the --no-cache option did the trick!
