### ISSUE TITLE
error trying to run tool from docker hub

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/mergin-db-sync#39]
Hi Guys

very sorry to bother again. 

when trying to build the container from docker hub [lutraconsulting/mergin-db-sync](https://hub.docker.com/r/lutraconsulting/mergin-db-sync) I get the following issues:

1. just running "sudo docker run --name mergin_db_sync -it lutraconsulting/mergin-db-sync:latest" throws a manifest error:
![image](https://user-images.githubusercontent.com/51097011/115369971-ec01bc80-a1c8-11eb-9e4e-185047e99fff.png)

I then rather explicitly state the tag "sudo docker run --name mergin_db_sync -it lutraconsulting/mergin-db-sync:1.0.2" which works and builds the image.

2. The built container's default command is /bin/bash :
![image](https://user-images.githubusercontent.com/51097011/115370282-33884880-a1c9-11eb-80f6-4e0ced086689.png)

So after the container is built I am  redirected inside the container and get the following errors when trying to set the environmental variables (-e) and trying to run the daemon. complete command and error:

![image](https://user-images.githubusercontent.com/51097011/115373353-14d78100-a1cc-11eb-9ec6-ad34068d9683.png)

any help will be appreciated 🙂
thank you

**Comment by wonder-sk** [comment]
hi @HugoP27 

I think in the first case you typed 'lates' instead of 'latest'... In any case I would recommend to use explicit version tag as you did later.

In the second case... if you have multi-line command, each line of the command that continues to the next line needs to end with a backslash character `\` otherwise the further lines will be run as separate commands.

**Comment by wonder-sk** [comment]
For the record, I have now added also "latest" tag to mergin-db-sync which was not there before...

**Comment by HugoP27** [comment]
Hi @wonder-sk 

Thanks for the quick response, I've tried adding the \ , but then get another error:

![image](https://user-images.githubusercontent.com/51097011/115385222-2e7ec580-a1d8-11eb-9641-8e55857a8614.png)

I think this might be a user error 🙈, due to my lack of docker knowledge, if so please let me know then it might be better for me to contact you directly for assistance/consulting.

**Comment by wonder-sk** [comment]
Oops sorry I think the getting started doc got it wrong :man_facepalming: ... this is the correct version:
```
$ sudo docker run --name mergin_db_sync -it \
  -e DB_CONN_INFO="host=myhost.com dbname=db-sync user=postgres password=top_secret" \
  -e DB_SCHEMA_MODIFIED=sync_data \
  -e DB_SCHEMA_BASE=sync_base \
  -e MERGIN_USERNAME=john \
  -e MERGIN_PASSWORD=myStrongPassword \
  -e MERGIN_PROJECT_NAME=john/db-sync \
  -e MERGIN_SYNC_FILE=sync_db.gpkg \
  lutraconsulting/mergin-db-sync:latest python3 dbsync_daemon.py --init-from-db
```

(the first line should not include container image, it should be on the last line)

**Comment by HugoP27** [comment]
Thanks a lot @wonder-sk this issue is resolved, works now, I have a different issue now, but will open a different issue for record keeping purposes

**Comment by wonder-sk** [comment]
Cool - I have also fixed the quick start guide
