### ISSUE TITLE
File/image sync

### ISSUE THREAD

**Issue by stevenjh** [lutraconsulting/mergin-db-sync#47]
I'm curious is there are any plans to implement/integrate related files/image sync within this tool?

There would be a wide range of places that people would be targeting for files to go but if we started with a local file system it should be easy to branch that out. 

I'd put my hand up for working on an azure blob storage connector.

**Comment by wonder-sk** [comment]
This is on the wish list, but there has not been enough interest yet to start implementation - with possibly many different storage providers to support (Dropbox, Google Drive, S3, Sharepoint, ...)

It should be fairly straightforward to get a one-way sync of files running (two-way sync is probably not as crucial here as with databases).

Please let us know if you would like us to add such feature within a contract... Or if you are a developer, we are happy to accept pull requests to make the db-sync better!

**Comment by stevenjh** [comment]
Thanks for the feedback! I can pull some python together so would have a look and see if I can figure out something.
We'd need to handle multiple photos per feature as the first step,  so the handling of related features in Input is a bigger priority and barrier to subscription right now.

**Comment by saberraz** [comment]
@stevenjh support for multiple photos to a single feature has been added to Input 0.9.9 (sorry it is off-topic to the ticket, but wanted to let you know :-D)

**Comment by wonder-sk** [comment]
Sync of images to a third party data storage is now possible with mergin-media-sync tool - see https://github.com/lutraconsulting/mergin-media-sync
