### ISSUE TITLE
db sync with Mergin CE

### ISSUE THREAD

**Issue by shazybug-dev** [lutraconsulting/mergin-db-sync#53]
Hello

I have set up Mergin CE as a docker on my server.  I have also installed db sync in docker.  How do I point db sync to the local installation of mergin server?

The "Running with Docker" commands asks for MERGIN_USERNAME and MERGIN_PASSWORD.  I assume this refers to the public cloud mergin server:
```
sudo docker run -it \
  -e DB_CONN_INFO="host=myhost.com dbname=mergin_dbsync user=postgres password=top_secret" \
  -e DB_SCHEMA_MODIFIED=sync_main \
  -e DB_SCHEMA_BASE=sync_base \
  -e MERGIN_USERNAME=john \
  -e MERGIN_PASSWORD=myStrongPassword \
  -e MERGIN_PROJECT_NAME=john/my_project \
  -e MERGIN_SYNC_FILE=sync_db.gpkg \
  lutraconsulting/mergin-db-sync:latest \
  python3 dbsync_daemon.py --init-from-gpkg
```

Would really appreciate some help.

**Comment by PeterPetrik** [comment]
You can use `MERGIN_URL` environment variable to point to your custom URL
