### ISSUE TITLE
"Output GPKG file does not exist"

### ISSUE THREAD

**Issue by shazybug-dev** [lutraconsulting/mergin-db-sync#55]
Hello

I have tried to follow the docker setup instructions on my synology NAS but receive an error when I try to initiate it from gpkg.
Below are screenshots of my container setup, I also mounted the /tmp/dbsync folder.  I think my configuration is able to login to both the postgres dB and my local instance of mergin.  Not sure where I am going wrong?  I have also created the schemas in postgres using pgAdmin.  Not sure if it should be in the env variables as well.

![container ENV](https://user-images.githubusercontent.com/63399852/139711689-04fe4922-6be7-419a-87e1-f81178d56015.png)

![mergin project](https://user-images.githubusercontent.com/63399852/139711736-fa0b2bec-9f37-435c-9d94-2f2d11cea35f.png)

![error msg](https://user-images.githubusercontent.com/63399852/139711778-47c7c09d-c811-417b-9b5e-f1e0966790ce.png)

Once again, thank you in advance for the assistance.

**Comment by wonder-sk** [comment]
It looks like you have a space between `--` and `init-from-gpkg` ? It should be together `--init-from-gpkg` - probably that's why the option is not recognized correctly?

**Comment by shazybug-dev** [comment]
Thank you! Rookie error.  I now have this error, but I think I need to setup my project correctly.
![metadata error](https://user-images.githubusercontent.com/63399852/140308035-71d3c693-feb3-445d-8dc9-c57ccfe75ba9.png)

**Comment by wonder-sk** [comment]
It may be a good idea to remove your existing mergin-db-sync container and start a new one, in case there are some leftover files from the previous unsuccessful run...
